name: flutter_issue_tracker
description: Flutter Issue Tracker
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  bloc: ^8.0.3
  dartz: ^0.10.1
  data_connection_checker_nulls: ^0.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  flutter_screenutil: ^5.5.3+2
  fluttertoast: ^8.0.9
  get_it: ^7.2.0
  graphql_flutter: ^5.1.0
  intl: ^0.17.0
  pull_to_refresh: ^2.0.0
  stacked_themes: ^0.3.8+1
  stream_transform: ^2.0.0
  timeago: ^3.2.2

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_launcher_icons: ^0.9.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/ic_app.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/icon/

